title = "{{app_title}}" # title of your app

description = "{{app_description}}" # short description about your app

debug = true # run app in debug mode

# uncomment api's you want to use in your app
permissions = [
    # "filesystem",
    # "notification",
    # "process",
]

dev_server_url = "http://localhost:8889" # url of development server. DO NOT CHANGE

package_manager = "{{package_manager}}" # "npm" or "yarn"
