name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            target: i686-pc-windows-msvc
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Build project
        run: cargo +nightly build --out-dir ./dist/ --target i686-pc-windows-msvc --release --verbose -Z unstable-options

      - name: list directories
        run: dir ./dist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/velox.exe
          asset_name: velox-cli.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "CLI tool for velox"
